development:
    cloud_name:  dik7gobbe
    api_key:  572151838727438
    api_secret:  MRl_PgmaO6tOgR8z7cQ6eXErhPo

production:
    cloud_name:  dik7gobbe
    api_key:  572151838727438
    api_secret:  MRl_PgmaO6tOgR8z7cQ6eXErhPo
